# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_CreditCardList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS_CreditCardList
  pod 'Kingfisher'
  pod 'lottie-ios'	
  pod 'Firebase/Database'

end
